on:
  push:
    branches:
    - main
    - release/*
jobs:
  web:
    name: Deploy web for jhaishna
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to ec2
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}  
